dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -U pip
  - pip install sphinx sphinx_rtd_theme
script:
  - cd docs
  - make html
deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script:
      - eval "$(ssh-agent -s)"
      - openssl aes-256-cbc -K $encrypted_151fbad3b0ea_key -iv $encrypted_151fbad3b0ea_iv -in deploy-key.enc -out deploy-key -d
      - chmod 600 deploy-key
      - ssh-add deploy-key

      # commit the assets in docs/build/ to the gh-pages branch and push to GitHub using SSH
      - ./node_modules/.bin/gh-pages -d docs/build/ -b gh-pages -r git@github.com:${TRAVIS_REPO_SLUG}.git
    on:
      branch: dev
