dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -U pip
  - pip install sphinx sphinx_rtd_theme
script:
  - cd docs
  - make html
deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: ./.travis-deploy.sh
    on:
      branch: dev
