language: node_js

node_js:
  - cd docs
  - make html

script:
  # test/lint and build the project
  - npm run lint
  - npm run build

deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: ./.travis-deploy.sh
    on:
      branch: dev
