dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - npm install gh-pages
  - pip install -U pip
  - pip install sphinx sphinx_rtd_theme
script:
  - openssl aes-256-cbc -K $encrypted_151fbad3b0ea_key -iv $encrypted_151fbad3b0ea_iv -in deploy-key.enc -out deploy-key -d
  - chmod 600 deploy-key
  - eval `ssh-agent -s`
  - ssh-add deploy-key
  - pwd
  - cd docs
  - make html
  - cd ..
  - pwd
  - ./node_modules/.bin/gh-pages
deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: ./.travis-deploy.sh
    on:
      branch: dev
