language: node_js

node_js:
  - node

install:
  - pip install sphinx sphinx_rtd_theme

script:
  - cd docs
  - make html

deploy:
  - provider: script
    skip_cleanup: true # do not delete the built assets
    script: ./.travis-deploy.sh
    on:
      branch: dev
